name: Build Module
on:
  push:

jobs:
  build_module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run script
        run: |
          cd .github/scripts
          mv make_module.sh ../../
          cd ../..
          chmod +x make_module.sh
          ./make_module.sh

      - name: Upload module
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Magisk Module
          path: module.zip
